name: continuous deployment workflow
on:
    push:
        branches:
            - main
defaults:
    run:
        shell: bash
        working-directory: .
jobs:
    deploy:
        name: 'Deploy'
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: deploy to remote server
              uses: burnett01/rsync-deployments@7.0.0
              with:
                  switches: -avzr --delete
                  path: .
                  remote_path: /home/ubuntu/projects/terminal-chatroom
                  remote_host: ${{ secrets.REMOTE_HOST }}
                  remote_user: ${{ secrets.REMOTE_USER }}
                  remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: build and run server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.REMOTE_HOST}}
                  username: ${{ secrets.REMOTE_USER}}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd ./projects/terminal-chatroom/build
                      echo "killing server"
                      kill $(pidof server)
                      echo "killed server"
                      make clean
                      make server
                      echo "starting server"
                      ./server &
                      echo "server started"
                      exit
